name: Deploy para HostGator

# Dispara o deploy quando um push for feito na branch 'main'
on:
  push:
    branches:
      - main # Altere para a branch desejada, se necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checar o código
      - name: Checar o código
        uses: actions/checkout@v2

      # Step 2: Configurar SSH usando a chave privada armazenada no GitHub Secret
      - name: Configurar SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 50.6.138.75 >> ~/.ssh/known_hosts

      # Step 3: Executar o deploy no servidor HostGator
      - name: Deploy via SSH
        env:
          REPO_DIR: "/home/zanott61/api.zanottofelipe.com" # Substitua pelo diretório do subdomínio no HostGator
        run: |
          ssh zanott61@50.6.138.75 << EOF
            cd $REPO_DIR
            git pull origin main  # Puxa as alterações do repositório
            # Outros comandos de deploy, se necessário
          EOF
